prgrms-web-devcourse-final-project/WEB4_5_NOBREAKTIME_BE

- src/main/java/com/mallang/mallang_backend/domain/dashboard/controller/DashboardController.java
- src/main/java/com/mallang/mallang_backend/domain/quiz/expressionquiz/controller/ExpressionQuizController.java
- src/main/java/com/mallang/mallang_backend/domain/quiz/wordquiz/controller/WordQuizController.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/controller/ExpressionBookController.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbookitem/controller/ExpressionBookItemController.java
- src/main/java/com/mallang/mallang_backend/domain/video/learning/controller/VideoLearningQuizController.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/controller/VideoController.java
- src/main/java/com/mallang/mallang_backend/domain/videohistory/controller/VideoHistoryController.java
- src/main/java/com/mallang/mallang_backend/domain/voca/word/controller/WordController.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/controller/WordbookController.java
- src/main/java/com/mallang/mallang_backend/global/swagger/ErrorResponseCustomizer.java
#96 
- 예:
3. 성공 메시지 확인
Closes #96
모든 컨트롤러에 @PossibleErrors 어노테이션 추가해서 스웨거상으로 에러 응답 보이게 해놨습니다.
ErrorResponseCustomizer의 map으로 반환하는 부분 LinkedHashMap으로 변경했습니다. (응답 형식의 순서 보장이 필요하기 때문)
> ✨ feat: 모든 API에 PossibleErrors 추가

- docker-compose.yml
- prometheus.yml
- src/main/java/com/mallang/mallang_backend/domain/member/controller/MemberController.java
- src/main/java/com/mallang/mallang_backend/global/token/TokenService.java
- 로그아웃 시 액세스 토큰, 리프레시 토큰 모두 쿠키에서 사라집니다 (Null 처리)
- redis 에서도 리프레시 토큰 값이 삭제됩니다 (화이트 리스트로 사용)
Closes #{116}
프로메테우스 관련한 yml 설정은 바로 적용 후에 말씀 드릴게요. 
이후에 변경하시면 사용 가능하실 거예요 :)
> 🐛 fix: 로그아웃 시 액세스 토큰 삭제 및 프로메테우스 + 그라파나 설정 #116

- src/main/java/com/mallang/mallang_backend/global/exception/GlobalExceptionHandler.java
- src/test/java/com/mallang/mallang_backend/global/exception/GlobalExceptionHandlerTest.java
-> 임시 테스트 컨트롤러에 대한 예외 =>
- 예:
3. 성공 메시지 확인
#120 
"Redis 캐시 적용 필요" or "추후 프론트에서 토큰 연동"
+) AuthTest에서 Exception으로 예외처리가 되어서 4XX가 아닌 5XX으로 처리되는 문제가 있었습니다.
-> @ExceptionHandler(AuthorizationDeniedException.class)를 따로 더 추가해서 해결했습니다.
> ✨ feat: Global Exception Handler 상위 핸들러 추가

- src/main/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/video/youtube/client/YouTubeClient.java
- src/main/java/com/mallang/mallang_backend/domain/video/youtube/service/YoutubeService.java
- src/main/java/com/mallang/mallang_backend/global/config/AsyncConfig.java
- src/test/java/com/mallang/mallang_backend/domain/video/youtube/service/YoutubeServiceTest.java
- #109 
- 예:
3. 성공 메시지 확인
Closes #109
- nextPageToken을 이용해 50개 청크를 이어 요청하고, 최종적으로 원하는 개수(desiredCount)만큼 반환하도록 수정
- 원래 동기 로직을 분리하고, 이를 CompletableFuture + youtubeApiExecutor 스레드풀로 감싸는 fetchVideosByIdsAsync 메서드 구현
- YouTube API가 한 번에 최대 50개만 반환하기 때문에, 조회할 ID 리스트를 50개씩 청크(chunk)로 나눈 뒤 각각을 병렬 호출
- @TimeLimiter(name="youtubeService")로 비동기 호출에 5초 타임아웃 설정 (초과 시 TimeoutException → fallback)
- @Bulkhead(name="youtubeService", type=SEMAPHORE)로 동시 호출을 20개로 제한, 21번째부터 BulkheadFullException으로 즉시 거부
> ✨ feat: 영상 조회에 페이지네이션 추가, 로직 개선

- src/main/java/com/mallang/mallang_backend/domain/stt/converter/TranscriptParserImpl.java
- src/main/java/com/mallang/mallang_backend/domain/stt/converter/TranscriptSegment.java
- src/main/java/com/mallang/mallang_backend/domain/video/subtitle/repository/SubtitleRepository.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImpl.java
- src/main/java/com/mallang/mallang_backend/global/gpt/dto/GptSubtitleResponse.java
- src/main/java/com/mallang/mallang_backend/global/gpt/util/GptScriptProcessor.java
- src/test/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImplTest.java
- src/test/java/com/mallang/mallang_backend/global/gpt/util/GptScriptProcessorTest.java
- 이 PR이 해결하는 이슈 번호를 명시(예: ✨ feat: 사전 API 예문 추가 (#25))
- 이 부분은 등록 후 삭제해 주세요!
- #128 
- 예:
3. 성공 메시지 확인
Closes #128 
영상 분석 응답에 자막 ID를 포함하도록 변경했습니다. 수정 후 결과를 확인해 보니 정상적으로 동작하는 것 같습니다. 다만, 분석 로직은 제가 직접 구현한 부분이 아니라서 혹시 미흡한 점이 있을지 모르겠습니다. 검토해 주시면 바로 반영하겠습니다.
추가로, 한 번 분석되어 캐시에 저장된 영상에 대해 재조회할 때 키워드가 없는 자막이 누락되던 문제를 LEFT JOIN으로 수정해 모든 자막이 응답에 포함되도록 개선했습니다.
> 🐛 fix: 영상 분석 시 자막 ID 누락 오류 수정

- src/main/java/com/mallang/mallang_backend/domain/video/learning/service/impl/VideoLearningQuizServiceImpl.java
#131 
- 예:
3. 성공 메시지 확인
Closes #131
단어 퀴즈의 갯수 제한 해제
> ♻️ refactor: VideoLearningQuizServiceImpl에서 퀴즈 아이템 수 제한 로직 제거

- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/controller/ExpressionBookController.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/dto/ExpressionResponse.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/repository/ExpressionBookRepository.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/service/ExpressionBookService.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/service/impl/ExpressionBookServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbookitem/repository/ExpressionBookItemRepository.java
- src/test/java/com/mallang/mallang_backend/domain/sentence/expressionbook/ExpressionBookServiceImplTest2.java
-> `"expressionBookId": 1` 를 받아오므로, 특정 단어장들을 보기 위해선 프론트에서 필터처리 해야함.
-> videoId, videoTitle, thumbnailImageUrl, expressionBookId 추가. (expressionBookId를 응답하여 필터처리 가능하도록)
- 예:
3. 성공 메시지 확인
#151 
"Redis 캐시 적용 필요" or "추후 프론트에서 토큰 연동"
> ✨ feat: 표현 목록 조회 응답 수정 (#151)

- src/main/java/com/mallang/mallang_backend/domain/video/video/controller/VideoController.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/listener/VideoEventListener.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/service/VideoService.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImpl.java
- src/main/java/com/mallang/mallang_backend/global/config/AsyncConfig.java
- src/main/java/com/mallang/mallang_backend/global/exception/ErrorCode.java
- src/main/java/com/mallang/mallang_backend/global/util/youtube/YoutubeAudioExtractorImpl.java
- src/main/resources/messages.properties
- src/test/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImplTest.java
- 기본 로직
- curl로 SSE 적용 테스트 결과
- 동일한 영상에 대해 여러번 요청 시 동일한 영상이 분석중이라고 sse 전달
- [노션 페이지](https://www.notion.so/SSE-1f13550b7b558045acdac32559a9ae16?pvs=4)에 자세히 작성해뒀습니다.
Closes #143 
- 프론트에서 sse를 받을 수 있도록 변경 필요
- yml에 추가된 부분
```
bulkhead:
instances:
oauthUserLoginService:
maxConcurrentCalls: 20             # 최대 동시 처리 가능 요청 수
maxWaitDuration: 100ms             # 대기 시간 초과 시 예외 발생
youtubeService:
maxConcurrentCalls: 10             # 최대 동시 처리 가능 요청 수
maxWaitDuration: 200ms             # 대기 시간 초과 시 예외 발생
audioExtraction:
maxConcurrentCalls: 20              # 최대 동시 실행 허용 수
maxWaitDuration: 300s               # 슬롯이 없으면 최대 300초까지 대기
```
> ✨ feat: 영상 분석에 SSE 적용 및 이벤트 기반으로 변경 (#143)

- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/controller/WordbookController.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/dto/WordResponse.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/service/WordbookService.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/service/impl/WordbookServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbookitem/repository/WordbookItemRepository.java
---
-> "wordBookId": 1 를 받아오므로, 특정 단어장들을 보기 위해선 프론트에서 필터처리 해야함.
---
```
{
"code": "200",
"msg": "단어 목록이 조회되었습니다.",
"data": [
{
"word": "scene",
"pos": "명사",
"meaning": "장면",
"difficulty": "EASY",
"exampleSentence": "That scene was emotional.",
"translatedSentence": "그 장면은 감동적이었다.",
"videoId": "vid2",
"videoTitle": "표현영상2",
"imageUrl": "thumb2.jpg",
"subtitleId": 1003,
"createdAt": "2025-05-13T17:14:49.655899",
"wordBookId": 4
},
{
"word": "revenge",
"pos": "명사",
"meaning": "복수",
"difficulty": "NORMAL",
"exampleSentence": "He sought revenge.",
"translatedSentence": "그는 복수를 원했다.",
"videoId": "vid2",
"videoTitle": "표현영상2",
"imageUrl": "thumb2.jpg",
"subtitleId": 1004,
"createdAt": "2025-05-13T17:14:49.655899",
"wordBookId": 4
},
{
"word": "contract",
"pos": …
```
> ✨ feat: 단어 목록 조회 응답 수정 (#146)

- src/main/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/videohistory/controller/VideoHistoryController.java
- src/main/java/com/mallang/mallang_backend/domain/videohistory/repository/VideoHistoryRepository.java
- src/main/java/com/mallang/mallang_backend/domain/videohistory/service/VideoHistoryService.java
- src/main/java/com/mallang/mallang_backend/domain/videohistory/service/impl/VideoHistoryServiceImpl.java
- src/main/java/com/mallang/mallang_backend/global/constants/AppConstants.java
- src/test/java/com/mallang/mallang_backend/domain/videohistory/service/impl/VideoHistoryServiceImplTest.java
#161 
- 예:
3. 성공 메시지 확인
Closes #161 
페이징 추가 (파라미터 : 페이지, 페이지 사이즈)
50건 까지 히스토리 저장, 50건이 넘어가면 오래된 것 부터 순차 제거
> ✨ feat: VideoHistory 기능 보완

- src/main/java/com/mallang/mallang_backend/domain/quiz/expressionquiz/dto/ExpressionQuizItem.java
- src/main/java/com/mallang/mallang_backend/domain/quiz/expressionquiz/service/impl/ExpressionQuizServiceImpl.java
- src/test/java/com/mallang/mallang_backend/domain/quiz/expressionquiz/service/impl/ExpressionQuizServiceImplTest.java
> ✨ feat: 표현함 퀴즈 응답형식 수정 (#170)

- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/controller/ExpressionBookController.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/repository/ExpressionBookRepository.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/service/ExpressionBookService.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/service/impl/ExpressionBookServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbookitem/entity/ExpressionBookItem.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbookitem/repository/ExpressionBookItemRepository.java
- src/test/java/com/mallang/mallang_backend/domain/sentence/expressionbook/ExpressionBookServiceImplTest2.java
: 이와 같은 임시 데이터들이 있다고 가정했을 때
- 예:
3. 성공 메시지 확인
#183 
-> 단어장 목록 조회와 마찬가지로, validateExpressionBookIdsExist 메서드와 findExpressionBookItems 메서드, 그리고
return convertToExpressionResponses(items); 으로 구분지어서 구현함.
: 단어장 단어 조회와 마찬가지로, convertToExpressionResponses 메서드를 구현해봤는데
표현함 로직에 맞게 구현이 잘 된건지 확인 해주시면 감사하겠습니다..!
> ✨ feat: 표현 목록 응답 조회 (Param expressionbookIds) (#183)

- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/controller/ExpressionBookController.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/dto/DeleteExpressionsRequest.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/dto/ExpressionBookRequest.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/dto/ExpressionSaveRequest.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/dto/MoveExpressionsRequest.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/dto/UpdateExpressionBookNameRequest.java
- src/main/java/com/mallang/mallang_backend/domain/sentence/expressionbook/service/impl/ExpressionBookServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/controller/WordbookController.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/repository/WordbookRepository.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbook/service/impl/WordbookServiceImpl.java
- src/main/java/com/mallang/mallang_backend/global/exception/ErrorCode.java
- src/main/resources/messages.properties
- 예:
3. 성공 메시지 확인
#200 
"Redis 캐시 적용 필요" or "추후 프론트에서 토큰 연동"
`@transactional -> 제거` (@transactional(readOnly = true)가 클래스 단위로 되어있으므로)
```
for (ExpressionBook book : books) {
int expressionCount = expressionBookItemRepository.countByIdExpressionBookId(book.getId());
System.out.println(expressionCount);
}
```
-> 표현함에는, 표현함 추가 시 이름 중복 검증 로직을 추가 했어서, 단어장에도 있으면 좋을 것 같아 추가해봤습니다.
```
if (wordbookRepository.existsByMemberAndName(member, request.getName())) {
throw new ServiceException(DUPLICATE_WORDBOOK_NAME);
}
```
-> 표현함에서 @Valid 유효성 검증을 추가해봤습니다.
커밋 내역 [✨ feat: 표현함 - 요청 DTO에 유효성 검사 추가] 을 확인해주시면 감사하겠습니다!
> ♻️ refactor: 단어장/표현함 개선 (#200)

- src/main/java/com/mallang/mallang_backend/domain/quiz/wordquiz/service/impl/WordQuizServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbookitem/entity/WordStatus.java
- src/main/java/com/mallang/mallang_backend/domain/voca/wordbookitem/repository/WordbookItemRepositoryCustomImpl.java
- 복습 주기가 리터럴로 사용되고 있어 WordStatus에 추가해 사용되도록 변경했습니다.
Closes #189
> ♻️  refactor: 단어 상태에 복습 주기를 포함하도록 리팩토링 (#189)

- src/main/java/com/mallang/mallang_backend/domain/videohistory/repository/VideoHistoryRepository.java
- src/main/java/com/mallang/mallang_backend/domain/videohistory/service/impl/VideoHistoryServiceImpl.java
- src/test/java/com/mallang/mallang_backend/domain/videohistory/service/impl/VideoHistoryServiceImplTest.java
#195 
- 예:
3. 성공 메시지 확인
Closes #195 
비디오 히스토리 50개 시 자동 삭제 -> 제거
최근 50개 (top50) 만 띄워주고, 테이블엔 계속 저장하는 것으로 수정
> ♻️ refactor: 비디오 히스토리 수정

- src/main/java/com/mallang/mallang_backend/domain/bookmark/controller/BookmarkController.java
- src/main/java/com/mallang/mallang_backend/domain/video/util/VideoUtils.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/dto/VideoDetail.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/dto/VideoResponse.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/entity/Videos.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/videohistory/dto/VideoHistoryResponse.java
- src/test/java/com/mallang/mallang_backend/domain/video/video/controller/VideoControllerTest.java
- src/test/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoQueryServiceTest.java
- src/test/java/com/mallang/mallang_backend/domain/video/video/service/impl/VideoServiceImplTest.java
#232 
- 예:
3. 성공 메시지 확인
Closes #232
영상 조회 응답에 영상 길이를 추가했습니다. PT11M55S와 같은 형식으로 나옵니다.
> ✨ feat: VideoResponse에 duration 필드 추가 및 관련 메서드 수정

- src/main/java/com/mallang/mallang_backend/domain/video/video/cache/VideoCacheClient.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/cache/service/VideoCacheRetryService.java
- src/main/java/com/mallang/mallang_backend/domain/video/youtube/service/YoutubeService.java
- src/test/java/com/mallang/mallang_backend/domain/video/video/cache/service/VideoCacheRetryServiceTest.java
- src/test/java/com/mallang/mallang_backend/domain/video/youtube/service/YoutubeServiceTest.java
✨ feat: 비디오 캐시 retry, YouTube 서비스 폴백 리팩토링, 로깅 및 테스트 추가
#239 
- 예:
3. 성공 메시지 확인
Closes #239 
1. VideoCacheRetryService 구현 및 Resilience4j Retry 적용
- Redis 캐시 조회 로직에 최대 5회 재시도 기능 추가
- 실패 시 fallbackGetCachedVideos 로 빈 CachedVideos 반환
2. fallbackSearchVideoIds 로직 리팩토링
- YoutubeService.fallbackSearchVideoIds에서 직접 예외 던지지 않고 VideoCacheRetryService 이용하도록 변경
3. 테스트 추가
> ✨ feat: 비디오 캐시 retry, YouTube 서비스 폴백 리팩토링, 로깅 및 테스트 추가

- build.gradle
- src/main/java/com/mallang/mallang_backend/domain/payment/quartz/job/AutoBillingJob.java
- src/main/java/com/mallang/mallang_backend/global/slack/SlackNotification.java
- src/main/java/com/mallang/mallang_backend/global/slack/SlackNotificationAspect.java
- src/main/java/com/mallang/mallang_backend/global/slack/SlackNotifier.java
- src/test/java/com/mallang/mallang_backend/domain/payment/quartz/listener/RetryJobListenerTest.java
- src/test/java/com/mallang/mallang_backend/global/slack/SlackNotifierTest.java
+ 📸 Screenshot or Test
이런 식으로 슬랙에 알림이 가도록 하는 서비스 + 애노테이션 추가했습니다.
애노테이션 적용하시면 어떤 메서드가 실행될 때에 자동으로 알림 전송됩니다!
저 같은 경우에는 자동 결제 스케줄에 적용해서 시작할 때 알림을 받고 최종 실패했을 때에도 알림을 받을 수 있도록 해 두었습니다. ㅎ.ㅎ 
혹시나 사용하실 분들 계시다면 적용해 주셔도 좋을 것 같고, 레질리언스 retry + 서킷 브케이커에도 추가해 놓고 싶은데 지금 테스트 코드 있는 부분에서 이렇게 하면... 말도 안 되게 울릴 것 같아서 배포 버전에만 추가해 놓도록 하겠습니다.
어제 새벽에 테스트 보내서 미안 미안해...~
Closes #{245}
> ✨ feat: 슬랙 알림 추가

- src/main/java/com/mallang/mallang_backend/domain/video/video/cache/VideoCacheClient.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/cache/quartz/job/CacheSchedulerJob.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/cache/service/CacheSchedulerService.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/cache/service/VideoCacheRetryService.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/dto/VideoListRequest.java
- src/main/java/com/mallang/mallang_backend/domain/video/youtube/service/YoutubeService.java
- src/main/java/com/mallang/mallang_backend/global/config/CacheConfig.java
- src/main/java/com/mallang/mallang_backend/global/config/QuartzConfig.java
- src/main/java/com/mallang/mallang_backend/global/constants/AppConstants.java
- src/test/java/com/mallang/mallang_backend/domain/video/youtube/service/YoutubeServiceTest.java
- src/test/java/com/mallang/mallang_backend/global/resilience4j/CustomBulkheadConfigTest.java
- src/test/java/com/mallang/mallang_backend/global/resilience4j/CustomRetryConfigTest.java
- src/test/java/com/mallang/mallang_backend/global/resilience4j/CustomTimeLimiterConfigTest.java
#235
- 예:
3. 성공 메시지 확인
#235
매 새벽 3, 4시 마다 영어, 일본어 영상 300개씩 요청합니다. 필터 거르면 140개정도 가져오는 것 같습니다.
> ✨ feat: 동영상 캐시 갱신을 위한 Quartz 스케줄러 작업 및 서비스 추가, 캐시 설정 개선

- src/main/java/com/mallang/mallang_backend/domain/quiz/expressionquiz/service/impl/ExpressionQuizServiceImpl.java
실서버에는 문제없이 저장이 잘 되던 표현함 퀴즈 결과인데, 로컬상에는 사진과 같이, 문제가 발생하면서
표현을 찾을 수 없으니 퀴즈 결과가 저장이 안되는 문제가 발생했습니다.
원인은 ExpressionBookItemId 생성 시 파라미터 순서가 뒤바뀌있던 문제여서, 엔티티 매핑이 안되어서 생긴 문제 같습니다.
제가 제대로 확인을 못했네요😓😓
프론트에서도 뒤바뀌어져 있어서 백엔드와 같이 프론트도 수정했습니다.
희한하네요.. 실서버에는 문제없이 잘 돌아가는데, 로컬에 문제가 생기다니..💀
- 예:
3. 성공 메시지 확인
Closes #280 
> 🐛 fix: 수정된 ExpressionBookItemId 순서로 저장 로직 개선

- src/main/java/com/mallang/mallang_backend/domain/video/learning/dto/VideoLearningExpressionQuizItem.java
- src/main/java/com/mallang/mallang_backend/domain/video/learning/dto/VideoLearningExpressionQuizListResponse.java
- src/main/java/com/mallang/mallang_backend/domain/video/learning/service/impl/VideoLearningQuizServiceImpl.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/cache/client/VideoCacheClient.java
- src/main/java/com/mallang/mallang_backend/domain/video/video/dto/VideoListRequest.java
- src/main/java/com/mallang/mallang_backend/global/config/CacheConfig.java
- src/test/java/com/mallang/mallang_backend/domain/video/video/cache/VideoCacheClientTest.java
#290 
- 예:
3. 성공 메시지 확인
Closes #290 
영상 조회에 short 영상도 포함시켰습니다. 로딩이 아주 살짝 느려졌습니다..
영상 학습 퀴즈에 캐싱을 적용했습니다. 영어 영상은 문제 없이 바로 바로 로딩이 되나, 일본어 영상은 라이브러리를 거쳐서 퀴즈를 뽑기 때문에 로딩 속도가 상당히 길어서 도입했습니다.
> ✨ feat: 영상 조회에 short 영상도 포함, 영상 학습 퀴즈 캐싱 적용
